from django.urls import path

from .views import (
    admin_report,
    api_index,
    dashboard_report,
    db_status,
    domain_login,
    freeze_interval,
    session_info,
    sign_out,
    templates_report,
    users_collection,
    users_detail,
    users_options,
    submit_upload,
    validate_upload,
    admin_approve,
    admin_reject,
    admin_consolidate,
    get_upload_flags,
    submit_flag_decisions,
    get_declined_rows_summary,
)

urlpatterns = [
    path('upload/<int:log_id>/flags/', get_upload_flags, name='get-upload-flags'),
    path('upload/<int:log_id>/flags/decide/', submit_flag_decisions, name='submit-flag-decisions'),
    path('upload/<int:log_id>/flags/declined-summary/', get_declined_rows_summary, name='get-declined-rows-summary'),
    path('', api_index, name='api-index'),
    path('db-status/', db_status, name='db-status'),
    path('dashboard/', dashboard_report, name='dashboard-report'),
    path('admin-report/', admin_report, name='admin-report'),
    path('templates/', templates_report, name='templates-report'),
    path('freeze-interval/', freeze_interval, name='freeze-interval'),
    path('users/', users_collection, name='users-collection'),
    path('users/options/', users_options, name='users-options'),
    path('users/<int:pk>/', users_detail, name='users-detail'),
    path('login/', domain_login, name='domain-login'),
    path('logout/', sign_out, name='sign-out'),
    path('session/', session_info, name='session-info'),
    path('upload/', submit_upload, name='submit-upload'),
    path('validate-upload/', validate_upload, name='validate-upload'),
    path('admin/approve/', admin_approve, name='admin-approve'),
    path('admin/reject/', admin_reject, name='admin-reject'),
    path('admin/consolidate/', admin_consolidate, name='admin-consolidate'),
]
